/**
 * Card and Action identifiers
 */
export const CARD_TYPES = {
  PROPERTY: 'PROPERTY',
  PROPERTY_WILD: 'PROPERTY_WILD',
  ACTION: 'ACTION',
  RENT: 'RENT',
  RENT_WILD: 'RENT_WILD',
  MONEY: 'MONEY',
  BUILDING: 'BUILDING'
};

export const ACTION_TYPES = {
  PASS_GO: 'PASS_GO',
  DEAL_BREAKER: 'DEAL_BREAKER',
  SLY_DEAL: 'SLY_DEAL',
  FORCED_DEAL: 'FORCED_DEAL',
  DEBT_COLLECTOR: 'DEBT_COLLECTOR',
  BIRTHDAY: 'BIRTHDAY',
  JUST_SAY_NO: 'JUST_SAY_NO',
  DOUBLE_RENT: 'DOUBLE_RENT',
  HOUSE: 'HOUSE',
  HOTEL: 'HOTEL'
};

export default { CARD_TYPES, ACTION_TYPES };
